//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "app_state")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub cash_balance: Decimal,
    pub updated_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

/*
# Need to add a new column? Example: add "notes" to holdings
# 1. Edit migration
nano naviin/migration/src/m20220101_000001_create_table.rs
# Add: .col(string(Holding::Notes))
# 2. Re-run migration
cd naviin/migration
cargo run
# 3. Re-generate entities
cd naviin
sea-orm-cli generate entity \
-u sqlite://db.sqlite \
-o src/entities
 */